### ISSUE TITLE
Need to upgrade EKS version

### ISSUE THREAD

**Issue by rddefauw** [aws-solutions-library-samples/guidance-for-sql-based-extraction-transformation-and-loading-with-apache-spark-on-amazon-eks#1]
### Describe the bug ###

The template uses 1.19 but that is no longer supported.

### To Reproduce ###

Follow the vanilla CDK deployment process.  

### Expected Result ###

Stack deploys.

### Actual Result ###

9:55:25 AM | CREATE_FAILED        | Custom::AWSCDK-EKS-Cluster               | eks_cluster/EKS/Re...e/Resource/Default
Received response status [FAILED] from custom resource. Message returned: unsupported Kubernetes version

**Comment by melodyyangaws** [comment]
upgraded to EKS1.24
