### ISSUE TITLE
Cloudformation build fails

### ISSUE THREAD

**Issue by ct-19** [aws-solutions-library-samples/guidance-for-sql-based-extraction-transformation-and-loading-with-apache-spark-on-amazon-eks#3]
### Describe the bug ###
Failed during build

### To Reproduce ###
Steps to reproduce the behavior

1. Launch using CloudFormation

### Expected Result ###
create_complete

### Actual Result ###
rollback_failed

### Other information: ###
1. Version of the Solution (e.g., v1.1.0):

    To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0027) AWS Serverless Bot Framework v1.2.0 - This AWS CloudFormation template helps you provision the AWS Serverless Bot Framework stack without worrying about creating and configuring the underlying AWS infrastructure_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  Solution:
    Data:
      ID: SO0027
      Version: 'v1.2.0'
```

2. Region where CloudFormation template is deployed (e.g., us-east-1): us-east-1
3. Did you make any change in the source code? If yes, what are the relevant changes (if publicly available)?: no
4. Troubleshooting steps attempted: cloudtrail logs, deleted, 3 attempts same results
5. Were there any errors in the Cloudwatch logs?: yes
6. Screenshots (please **DO NOT include sensitive information**):
7. Did you use the Sample Weather Service (please DO NOT include API KEY) ? Yes

### Stack Parameters ###
Cloudformation Stack Parameters (please **DO NOT include sensitive information** like S3 bucket name, IP address, credentials, etc):
1. Bot Name:
2. Bot Language:
3. Bot Gender:

### Additional context ###

BUILD errors 

CodeBuildExecutionWaiter15934973D | CREATE_FAILED | Received response status [FAILED] from custom resource. Message returned: Failed to build with status "FAILED" Logs: /aws/lambda/Automated-Data-Analytics-CodeBuildExecutionIsCompl-kyKaGPTJRI2F at FailedBuildError (/var/task/index.js:21702:10) at Runtime.isCompleteHandler [as handler] (/var/task/index.js:21681:13) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:95:5) (RequestId: 569ae2f2-c152-4858-91b3-b4dc6f97b94e)

Automated-Data-Analytics | ROLLBACK_IN_PROGRESS | The following resource(s) failed to create: [CodeBuildExecutionWaiter15934973D]. Rollback requested by user.

ROLLBACK errors

CodeBuildExecutionWaiter15934973D | DELETE_FAILED | Received response status [FAILED] from custom resource. Message returned: Failed to build with status "FAILED" Logs: /aws/lambda/Automated-Data-Analytics-CodeBuildExecutionWaiterH-GayY7jz1DaKA at FailedBuildError (/var/task/index.js:21702:10) at Runtime.onWaiterEventHandler [as handler] (/var/task/index.js:21627:13) at processTicksAndRejections (internal/process/task_queues.js:95:5) (RequestId: 4255475a-e7f0-4ce0-a238-0a2f305800b0)

Ada | ROLLBACK_FAILED | The following resource(s) failed to delete: [ApiServiceStack970277D1].

Ada-ApiServiceStack970277D1-HZV604LXVEYU | DELETE_FAILED | The following resource(s) failed to delete: [ApiTeardown7F2E4F4C].

**Comment by melodyyangaws** [comment]
wrong project. this is not Ada project.
